version: "3.9"
services:
  app:
    image: eclipse-temurin:17
    ports:
      - 8080:8080
    volumes:
      - ./spring_prj:/workspace
    working_dir: /workspace
    tty: true
    depends_on:
      - db # 「db」の後で起動
    

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}

volumes:
  db-store: